# Generated by Django 4.2.29 on 2026-03-05 11:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Назва філії")),
                ("address", models.CharField(max_length=255, verbose_name="Адреса")),
                (
                    "contact_phone",
                    models.CharField(max_length=20, verbose_name="Телефон"),
                ),
            ],
            options={
                "verbose_name": "Філія",
                "verbose_name_plural": "Філії",
                "db_table": "branches",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Прізвище"),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Ім'я")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="По батькові",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата народження"
                    ),
                ),
                (
                    "registered_at",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата реєстрації",
                    ),
                ),
                (
                    "total_visits",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Кількість візитів"
                    ),
                ),
            ],
            options={
                "verbose_name": "Клієнт",
                "verbose_name_plural": "Клієнти",
                "db_table": "clients",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="ClientCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Назва категорії"),
                ),
                (
                    "min_visits",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Мінімум відвідувань"
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Знижка (%)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категорія клієнта",
                "verbose_name_plural": "Категорії клієнтів",
                "db_table": "client_categories",
                "ordering": ["min_visits"],
            },
        ),
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Назва статі"
                    ),
                ),
            ],
            options={
                "verbose_name": "Стать",
                "verbose_name_plural": "Статі",
                "db_table": "genders",
            },
        ),
        migrations.CreateModel(
            name="Haircut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Назва стрижки"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Опис"
                    ),
                ),
                (
                    "duration_time",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Тривалість (хв)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "gender",
                    models.ForeignKey(
                        db_column="genders_gender_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="salon.gender",
                        verbose_name="Стать",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стрижка",
                "verbose_name_plural": "Стрижки",
                "db_table": "haircuts",
            },
        ),
        migrations.CreateModel(
            name="PricelistHead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid_from", models.DateField(verbose_name="Діє з")),
                (
                    "valid_to",
                    models.DateField(blank=True, null=True, verbose_name="Діє до"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        db_column="branches_branch_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="salon.branch",
                        verbose_name="Філія",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прайс-лист",
                "verbose_name_plural": "Прайс-листи",
                "db_table": "pricelist_head",
                "ordering": ["-valid_from"],
            },
        ),
        migrations.CreateModel(
            name="CompletedWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Дата виконання"
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Підсумкова вартість (грн)",
                    ),
                ),
                (
                    "check_id",
                    models.PositiveIntegerField(unique=True, verbose_name="Номер чека"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        db_column="branches_branch_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="salon.branch",
                        verbose_name="Філія",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        db_column="clients_client_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="works",
                        to="salon.client",
                        verbose_name="Клієнт",
                    ),
                ),
                (
                    "haircut",
                    models.ForeignKey(
                        db_column="haircuts_haircut_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="salon.haircut",
                        verbose_name="Стрижка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Виконана робота",
                "verbose_name_plural": "Виконані роботи",
                "db_table": "completed_works",
                "ordering": ["-work_date"],
            },
        ),
        migrations.AddField(
            model_name="client",
            name="category",
            field=models.ForeignKey(
                db_column="client_categories_category_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="salon.clientcategory",
                verbose_name="Категорія",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="gender",
            field=models.ForeignKey(
                db_column="genders_gender_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="salon.gender",
                verbose_name="Стать",
            ),
        ),
        migrations.CreateModel(
            name="PricelistHeadHaircut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Ціна (грн)",
                    ),
                ),
                (
                    "haircut",
                    models.ForeignKey(
                        db_column="haircuts_haircut_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="salon.haircut",
                        verbose_name="Стрижка",
                    ),
                ),
                (
                    "pricelist_head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="salon.pricelisthead",
                        verbose_name="Прайс-лист",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ціна стрижки",
                "verbose_name_plural": "Ціни стрижок",
                "db_table": "pricelist_head_haircuts",
                "unique_together": {("pricelist_head", "haircut")},
            },
        ),
    ]
